nav:
  - Home: index.md
  - projects
  - kubernetes
  - linux
  - containers
  - networking
  - cloud
  - delivery
  - iac
  - observability
  - security
  - self-hosted
  - storage
  - bootstrap
  # - incident-response
  - workstation

ignore_no_matches: true
